// Static LeetCode problem database
// Fields: number, title, difficulty, slug
// URL constructed at runtime: https://leetcode.com/problems/${slug}/description/

const LEETCODE_PROBLEMS = [
  { n: 1, t: "Two Sum", d: "Easy", s: "two-sum" },
  { n: 2, t: "Add Two Numbers", d: "Medium", s: "add-two-numbers" },
  { n: 3, t: "Longest Substring Without Repeating Characters", d: "Medium", s: "longest-substring-without-repeating-characters" },
  { n: 4, t: "Median of Two Sorted Arrays", d: "Hard", s: "median-of-two-sorted-arrays" },
  { n: 5, t: "Longest Palindromic Substring", d: "Medium", s: "longest-palindromic-substring" },
  { n: 6, t: "Zigzag Conversion", d: "Medium", s: "zigzag-conversion" },
  { n: 7, t: "Reverse Integer", d: "Medium", s: "reverse-integer" },
  { n: 8, t: "String to Integer (atoi)", d: "Medium", s: "string-to-integer-atoi" },
  { n: 9, t: "Palindrome Number", d: "Easy", s: "palindrome-number" },
  { n: 10, t: "Regular Expression Matching", d: "Hard", s: "regular-expression-matching" },
  { n: 11, t: "Container With Most Water", d: "Medium", s: "container-with-most-water" },
  { n: 12, t: "Integer to Roman", d: "Medium", s: "integer-to-roman" },
  { n: 13, t: "Roman to Integer", d: "Easy", s: "roman-to-integer" },
  { n: 14, t: "Longest Common Prefix", d: "Easy", s: "longest-common-prefix" },
  { n: 15, t: "3Sum", d: "Medium", s: "3sum" },
  { n: 16, t: "3Sum Closest", d: "Medium", s: "3sum-closest" },
  { n: 17, t: "Letter Combinations of a Phone Number", d: "Medium", s: "letter-combinations-of-a-phone-number" },
  { n: 18, t: "4Sum", d: "Medium", s: "4sum" },
  { n: 19, t: "Remove Nth Node From End of List", d: "Medium", s: "remove-nth-node-from-end-of-list" },
  { n: 20, t: "Valid Parentheses", d: "Easy", s: "valid-parentheses" },
  { n: 21, t: "Merge Two Sorted Lists", d: "Easy", s: "merge-two-sorted-lists" },
  { n: 22, t: "Generate Parentheses", d: "Medium", s: "generate-parentheses" },
  { n: 23, t: "Merge k Sorted Lists", d: "Hard", s: "merge-k-sorted-lists" },
  { n: 24, t: "Swap Nodes in Pairs", d: "Medium", s: "swap-nodes-in-pairs" },
  { n: 25, t: "Reverse Nodes in k-Group", d: "Hard", s: "reverse-nodes-in-k-group" },
  { n: 26, t: "Remove Duplicates from Sorted Array", d: "Easy", s: "remove-duplicates-from-sorted-array" },
  { n: 27, t: "Remove Element", d: "Easy", s: "remove-element" },
  { n: 28, t: "Find the Index of the First Occurrence in a String", d: "Easy", s: "find-the-index-of-the-first-occurrence-in-a-string" },
  { n: 29, t: "Divide Two Integers", d: "Medium", s: "divide-two-integers" },
  { n: 30, t: "Substring with Concatenation of All Words", d: "Hard", s: "substring-with-concatenation-of-all-words" },
  { n: 31, t: "Next Permutation", d: "Medium", s: "next-permutation" },
  { n: 32, t: "Longest Valid Parentheses", d: "Hard", s: "longest-valid-parentheses" },
  { n: 33, t: "Search in Rotated Sorted Array", d: "Medium", s: "search-in-rotated-sorted-array" },
  { n: 34, t: "Find First and Last Position of Element in Sorted Array", d: "Medium", s: "find-first-and-last-position-of-element-in-sorted-array" },
  { n: 35, t: "Search Insert Position", d: "Easy", s: "search-insert-position" },
  { n: 36, t: "Valid Sudoku", d: "Medium", s: "valid-sudoku" },
  { n: 37, t: "Sudoku Solver", d: "Hard", s: "sudoku-solver" },
  { n: 38, t: "Count and Say", d: "Medium", s: "count-and-say" },
  { n: 39, t: "Combination Sum", d: "Medium", s: "combination-sum" },
  { n: 40, t: "Combination Sum II", d: "Medium", s: "combination-sum-ii" },
  { n: 41, t: "First Missing Positive", d: "Hard", s: "first-missing-positive" },
  { n: 42, t: "Trapping Rain Water", d: "Hard", s: "trapping-rain-water" },
  { n: 43, t: "Multiply Strings", d: "Medium", s: "multiply-strings" },
  { n: 44, t: "Wildcard Matching", d: "Hard", s: "wildcard-matching" },
  { n: 45, t: "Jump Game II", d: "Medium", s: "jump-game-ii" },
  { n: 46, t: "Permutations", d: "Medium", s: "permutations" },
  { n: 47, t: "Permutations II", d: "Medium", s: "permutations-ii" },
  { n: 48, t: "Rotate Image", d: "Medium", s: "rotate-image" },
  { n: 49, t: "Group Anagrams", d: "Medium", s: "group-anagrams" },
  { n: 50, t: "Pow(x, n)", d: "Medium", s: "powx-n" },
  { n: 51, t: "N-Queens", d: "Hard", s: "n-queens" },
  { n: 52, t: "N-Queens II", d: "Hard", s: "n-queens-ii" },
  { n: 53, t: "Maximum Subarray", d: "Medium", s: "maximum-subarray" },
  { n: 54, t: "Spiral Matrix", d: "Medium", s: "spiral-matrix" },
  { n: 55, t: "Jump Game", d: "Medium", s: "jump-game" },
  { n: 56, t: "Merge Intervals", d: "Medium", s: "merge-intervals" },
  { n: 57, t: "Insert Interval", d: "Medium", s: "insert-interval" },
  { n: 58, t: "Length of Last Word", d: "Easy", s: "length-of-last-word" },
  { n: 59, t: "Spiral Matrix II", d: "Medium", s: "spiral-matrix-ii" },
  { n: 60, t: "Permutation Sequence", d: "Hard", s: "permutation-sequence" },
  { n: 61, t: "Rotate List", d: "Medium", s: "rotate-list" },
  { n: 62, t: "Unique Paths", d: "Medium", s: "unique-paths" },
  { n: 63, t: "Unique Paths II", d: "Medium", s: "unique-paths-ii" },
  { n: 64, t: "Minimum Path Sum", d: "Medium", s: "minimum-path-sum" },
  { n: 65, t: "Valid Number", d: "Hard", s: "valid-number" },
  { n: 66, t: "Plus One", d: "Easy", s: "plus-one" },
  { n: 67, t: "Add Binary", d: "Easy", s: "add-binary" },
  { n: 68, t: "Text Justification", d: "Hard", s: "text-justification" },
  { n: 69, t: "Sqrt(x)", d: "Easy", s: "sqrtx" },
  { n: 70, t: "Climbing Stairs", d: "Easy", s: "climbing-stairs" },
  { n: 71, t: "Simplify Path", d: "Medium", s: "simplify-path" },
  { n: 72, t: "Edit Distance", d: "Medium", s: "edit-distance" },
  { n: 73, t: "Set Matrix Zeroes", d: "Medium", s: "set-matrix-zeroes" },
  { n: 74, t: "Search a 2D Matrix", d: "Medium", s: "search-a-2d-matrix" },
  { n: 75, t: "Sort Colors", d: "Medium", s: "sort-colors" },
  { n: 76, t: "Minimum Window Substring", d: "Hard", s: "minimum-window-substring" },
  { n: 77, t: "Combinations", d: "Medium", s: "combinations" },
  { n: 78, t: "Subsets", d: "Medium", s: "subsets" },
  { n: 79, t: "Word Search", d: "Medium", s: "word-search" },
  { n: 80, t: "Remove Duplicates from Sorted Array II", d: "Medium", s: "remove-duplicates-from-sorted-array-ii" },
  { n: 81, t: "Search in Rotated Sorted Array II", d: "Medium", s: "search-in-rotated-sorted-array-ii" },
  { n: 82, t: "Remove Duplicates from Sorted List II", d: "Medium", s: "remove-duplicates-from-sorted-list-ii" },
  { n: 83, t: "Remove Duplicates from Sorted List", d: "Easy", s: "remove-duplicates-from-sorted-list" },
  { n: 84, t: "Largest Rectangle in Histogram", d: "Hard", s: "largest-rectangle-in-histogram" },
  { n: 85, t: "Maximal Rectangle", d: "Hard", s: "maximal-rectangle" },
  { n: 86, t: "Partition List", d: "Medium", s: "partition-list" },
  { n: 87, t: "Scramble String", d: "Hard", s: "scramble-string" },
  { n: 88, t: "Merge Sorted Array", d: "Easy", s: "merge-sorted-array" },
  { n: 89, t: "Gray Code", d: "Medium", s: "gray-code" },
  { n: 90, t: "Subsets II", d: "Medium", s: "subsets-ii" },
  { n: 91, t: "Decode Ways", d: "Medium", s: "decode-ways" },
  { n: 92, t: "Reverse Linked List II", d: "Medium", s: "reverse-linked-list-ii" },
  { n: 93, t: "Restore IP Addresses", d: "Medium", s: "restore-ip-addresses" },
  { n: 94, t: "Binary Tree Inorder Traversal", d: "Easy", s: "binary-tree-inorder-traversal" },
  { n: 95, t: "Unique Binary Search Trees II", d: "Medium", s: "unique-binary-search-trees-ii" },
  { n: 96, t: "Unique Binary Search Trees", d: "Medium", s: "unique-binary-search-trees" },
  { n: 97, t: "Interleaving String", d: "Medium", s: "interleaving-string" },
  { n: 98, t: "Validate Binary Search Tree", d: "Medium", s: "validate-binary-search-tree" },
  { n: 99, t: "Recover Binary Search Tree", d: "Medium", s: "recover-binary-search-tree" },
  { n: 100, t: "Same Tree", d: "Easy", s: "same-tree" },
  { n: 101, t: "Symmetric Tree", d: "Easy", s: "symmetric-tree" },
  { n: 102, t: "Binary Tree Level Order Traversal", d: "Medium", s: "binary-tree-level-order-traversal" },
  { n: 103, t: "Binary Tree Zigzag Level Order Traversal", d: "Medium", s: "binary-tree-zigzag-level-order-traversal" },
  { n: 104, t: "Maximum Depth of Binary Tree", d: "Easy", s: "maximum-depth-of-binary-tree" },
  { n: 105, t: "Construct Binary Tree from Preorder and Inorder Traversal", d: "Medium", s: "construct-binary-tree-from-preorder-and-inorder-traversal" },
  { n: 106, t: "Construct Binary Tree from Inorder and Postorder Traversal", d: "Medium", s: "construct-binary-tree-from-inorder-and-postorder-traversal" },
  { n: 107, t: "Binary Tree Level Order Traversal II", d: "Medium", s: "binary-tree-level-order-traversal-ii" },
  { n: 108, t: "Convert Sorted Array to Binary Search Tree", d: "Easy", s: "convert-sorted-array-to-binary-search-tree" },
  { n: 110, t: "Balanced Binary Tree", d: "Easy", s: "balanced-binary-tree" },
  { n: 111, t: "Minimum Depth of Binary Tree", d: "Easy", s: "minimum-depth-of-binary-tree" },
  { n: 112, t: "Path Sum", d: "Easy", s: "path-sum" },
  { n: 113, t: "Path Sum II", d: "Medium", s: "path-sum-ii" },
  { n: 114, t: "Flatten Binary Tree to Linked List", d: "Medium", s: "flatten-binary-tree-to-linked-list" },
  { n: 115, t: "Distinct Subsequences", d: "Hard", s: "distinct-subsequences" },
  { n: 116, t: "Populating Next Right Pointers in Each Node", d: "Medium", s: "populating-next-right-pointers-in-each-node" },
  { n: 117, t: "Populating Next Right Pointers in Each Node II", d: "Medium", s: "populating-next-right-pointers-in-each-node-ii" },
  { n: 118, t: "Pascal's Triangle", d: "Easy", s: "pascals-triangle" },
  { n: 119, t: "Pascal's Triangle II", d: "Easy", s: "pascals-triangle-ii" },
  { n: 120, t: "Triangle", d: "Medium", s: "triangle" },
  { n: 121, t: "Best Time to Buy and Sell Stock", d: "Easy", s: "best-time-to-buy-and-sell-stock" },
  { n: 122, t: "Best Time to Buy and Sell Stock II", d: "Medium", s: "best-time-to-buy-and-sell-stock-ii" },
  { n: 123, t: "Best Time to Buy and Sell Stock III", d: "Hard", s: "best-time-to-buy-and-sell-stock-iii" },
  { n: 124, t: "Binary Tree Maximum Path Sum", d: "Hard", s: "binary-tree-maximum-path-sum" },
  { n: 125, t: "Valid Palindrome", d: "Easy", s: "valid-palindrome" },
  { n: 127, t: "Word Ladder", d: "Hard", s: "word-ladder" },
  { n: 128, t: "Longest Consecutive Sequence", d: "Medium", s: "longest-consecutive-sequence" },
  { n: 129, t: "Sum Root to Leaf Numbers", d: "Medium", s: "sum-root-to-leaf-numbers" },
  { n: 130, t: "Surrounded Regions", d: "Medium", s: "surrounded-regions" },
  { n: 131, t: "Palindrome Partitioning", d: "Medium", s: "palindrome-partitioning" },
  { n: 133, t: "Clone Graph", d: "Medium", s: "clone-graph" },
  { n: 134, t: "Gas Station", d: "Medium", s: "gas-station" },
  { n: 136, t: "Single Number", d: "Easy", s: "single-number" },
  { n: 138, t: "Copy List with Random Pointer", d: "Medium", s: "copy-list-with-random-pointer" },
  { n: 139, t: "Word Break", d: "Medium", s: "word-break" },
  { n: 140, t: "Word Break II", d: "Hard", s: "word-break-ii" },
  { n: 141, t: "Linked List Cycle", d: "Easy", s: "linked-list-cycle" },
  { n: 142, t: "Linked List Cycle II", d: "Medium", s: "linked-list-cycle-ii" },
  { n: 143, t: "Reorder List", d: "Medium", s: "reorder-list" },
  { n: 144, t: "Binary Tree Preorder Traversal", d: "Easy", s: "binary-tree-preorder-traversal" },
  { n: 145, t: "Binary Tree Postorder Traversal", d: "Easy", s: "binary-tree-postorder-traversal" },
  { n: 146, t: "LRU Cache", d: "Medium", s: "lru-cache" },
  { n: 148, t: "Sort List", d: "Medium", s: "sort-list" },
  { n: 149, t: "Max Points on a Line", d: "Hard", s: "max-points-on-a-line" },
  { n: 150, t: "Evaluate Reverse Polish Notation", d: "Medium", s: "evaluate-reverse-polish-notation" },
  { n: 151, t: "Reverse Words in a String", d: "Medium", s: "reverse-words-in-a-string" },
  { n: 152, t: "Maximum Product Subarray", d: "Medium", s: "maximum-product-subarray" },
  { n: 153, t: "Find Minimum in Rotated Sorted Array", d: "Medium", s: "find-minimum-in-rotated-sorted-array" },
  { n: 154, t: "Find Minimum in Rotated Sorted Array II", d: "Hard", s: "find-minimum-in-rotated-sorted-array-ii" },
  { n: 155, t: "Min Stack", d: "Medium", s: "min-stack" },
  { n: 160, t: "Intersection of Two Linked Lists", d: "Easy", s: "intersection-of-two-linked-lists" },
  { n: 162, t: "Find Peak Element", d: "Medium", s: "find-peak-element" },
  { n: 167, t: "Two Sum II - Input Array Is Sorted", d: "Medium", s: "two-sum-ii-input-array-is-sorted" },
  { n: 169, t: "Majority Element", d: "Easy", s: "majority-element" },
  { n: 189, t: "Rotate Array", d: "Medium", s: "rotate-array" },
  { n: 190, t: "Reverse Bits", d: "Easy", s: "reverse-bits" },
  { n: 191, t: "Number of 1 Bits", d: "Easy", s: "number-of-1-bits" },
  { n: 198, t: "House Robber", d: "Medium", s: "house-robber" },
  { n: 199, t: "Binary Tree Right Side View", d: "Medium", s: "binary-tree-right-side-view" },
  { n: 200, t: "Number of Islands", d: "Medium", s: "number-of-islands" },
  { n: 202, t: "Happy Number", d: "Easy", s: "happy-number" },
  { n: 203, t: "Remove Linked List Elements", d: "Easy", s: "remove-linked-list-elements" },
  { n: 206, t: "Reverse Linked List", d: "Easy", s: "reverse-linked-list" },
  { n: 207, t: "Course Schedule", d: "Medium", s: "course-schedule" },
  { n: 208, t: "Implement Trie (Prefix Tree)", d: "Medium", s: "implement-trie-prefix-tree" },
  { n: 210, t: "Course Schedule II", d: "Medium", s: "course-schedule-ii" },
  { n: 211, t: "Design Add and Search Words Data Structure", d: "Medium", s: "design-add-and-search-words-data-structure" },
  { n: 212, t: "Word Search II", d: "Hard", s: "word-search-ii" },
  { n: 213, t: "House Robber II", d: "Medium", s: "house-robber-ii" },
  { n: 215, t: "Kth Largest Element in an Array", d: "Medium", s: "kth-largest-element-in-an-array" },
  { n: 217, t: "Contains Duplicate", d: "Easy", s: "contains-duplicate" },
  { n: 219, t: "Contains Duplicate II", d: "Easy", s: "contains-duplicate-ii" },
  { n: 221, t: "Maximal Square", d: "Medium", s: "maximal-square" },
  { n: 224, t: "Basic Calculator", d: "Hard", s: "basic-calculator" },
  { n: 225, t: "Implement Stack using Queues", d: "Easy", s: "implement-stack-using-queues" },
  { n: 226, t: "Invert Binary Tree", d: "Easy", s: "invert-binary-tree" },
  { n: 227, t: "Basic Calculator II", d: "Medium", s: "basic-calculator-ii" },
  { n: 228, t: "Summary Ranges", d: "Easy", s: "summary-ranges" },
  { n: 230, t: "Kth Smallest Element in a BST", d: "Medium", s: "kth-smallest-element-in-a-bst" },
  { n: 234, t: "Palindrome Linked List", d: "Easy", s: "palindrome-linked-list" },
  { n: 235, t: "Lowest Common Ancestor of a Binary Search Tree", d: "Medium", s: "lowest-common-ancestor-of-a-binary-search-tree" },
  { n: 236, t: "Lowest Common Ancestor of a Binary Tree", d: "Medium", s: "lowest-common-ancestor-of-a-binary-tree" },
  { n: 237, t: "Delete Node in a Linked List", d: "Medium", s: "delete-node-in-a-linked-list" },
  { n: 238, t: "Product of Array Except Self", d: "Medium", s: "product-of-array-except-self" },
  { n: 239, t: "Sliding Window Maximum", d: "Hard", s: "sliding-window-maximum" },
  { n: 240, t: "Search a 2D Matrix II", d: "Medium", s: "search-a-2d-matrix-ii" },
  { n: 242, t: "Valid Anagram", d: "Easy", s: "valid-anagram" },
  { n: 252, t: "Meeting Rooms", d: "Easy", s: "meeting-rooms" },
  { n: 253, t: "Meeting Rooms II", d: "Medium", s: "meeting-rooms-ii" },
  { n: 261, t: "Graph Valid Tree", d: "Medium", s: "graph-valid-tree" },
  { n: 268, t: "Missing Number", d: "Easy", s: "missing-number" },
  { n: 269, t: "Alien Dictionary", d: "Hard", s: "alien-dictionary" },
  { n: 271, t: "Encode and Decode Strings", d: "Medium", s: "encode-and-decode-strings" },
  { n: 278, t: "First Bad Version", d: "Easy", s: "first-bad-version" },
  { n: 283, t: "Move Zeroes", d: "Easy", s: "move-zeroes" },
  { n: 287, t: "Find the Duplicate Number", d: "Medium", s: "find-the-duplicate-number" },
  { n: 295, t: "Find Median from Data Stream", d: "Hard", s: "find-median-from-data-stream" },
  { n: 297, t: "Serialize and Deserialize Binary Tree", d: "Hard", s: "serialize-and-deserialize-binary-tree" },
  { n: 300, t: "Longest Increasing Subsequence", d: "Medium", s: "longest-increasing-subsequence" },
  { n: 303, t: "Range Sum Query - Immutable", d: "Easy", s: "range-sum-query-immutable" },
  { n: 309, t: "Best Time to Buy and Sell Stock with Cooldown", d: "Medium", s: "best-time-to-buy-and-sell-stock-with-cooldown" },
  { n: 310, t: "Minimum Height Trees", d: "Medium", s: "minimum-height-trees" },
  { n: 322, t: "Coin Change", d: "Medium", s: "coin-change" },
  { n: 323, t: "Number of Connected Components in an Undirected Graph", d: "Medium", s: "number-of-connected-components-in-an-undirected-graph" },
  { n: 328, t: "Odd Even Linked List", d: "Medium", s: "odd-even-linked-list" },
  { n: 332, t: "Reconstruct Itinerary", d: "Hard", s: "reconstruct-itinerary" },
  { n: 338, t: "Counting Bits", d: "Easy", s: "counting-bits" },
  { n: 340, t: "Longest Substring with At Most K Distinct Characters", d: "Medium", s: "longest-substring-with-at-most-k-distinct-characters" },
  { n: 344, t: "Reverse String", d: "Easy", s: "reverse-string" },
  { n: 347, t: "Top K Frequent Elements", d: "Medium", s: "top-k-frequent-elements" },
  { n: 355, t: "Design Twitter", d: "Medium", s: "design-twitter" },
  { n: 371, t: "Sum of Two Integers", d: "Medium", s: "sum-of-two-integers" },
  { n: 374, t: "Guess Number Higher or Lower", d: "Easy", s: "guess-number-higher-or-lower" },
  { n: 380, t: "Insert Delete GetRandom O(1)", d: "Medium", s: "insert-delete-getrandom-o1" },
  { n: 383, t: "Ransom Note", d: "Easy", s: "ransom-note" },
  { n: 392, t: "Is Subsequence", d: "Easy", s: "is-subsequence" },
  { n: 394, t: "Decode String", d: "Medium", s: "decode-string" },
  { n: 395, t: "Longest Substring with At Least K Repeating Characters", d: "Medium", s: "longest-substring-with-at-least-k-repeating-characters" },
  { n: 399, t: "Evaluate Division", d: "Medium", s: "evaluate-division" },
  { n: 404, t: "Sum of Left Leaves", d: "Easy", s: "sum-of-left-leaves" },
  { n: 416, t: "Partition Equal Subset Sum", d: "Medium", s: "partition-equal-subset-sum" },
  { n: 417, t: "Pacific Atlantic Water Flow", d: "Medium", s: "pacific-atlantic-water-flow" },
  { n: 424, t: "Longest Repeating Character Replacement", d: "Medium", s: "longest-repeating-character-replacement" },
  { n: 435, t: "Non-overlapping Intervals", d: "Medium", s: "non-overlapping-intervals" },
  { n: 437, t: "Path Sum III", d: "Medium", s: "path-sum-iii" },
  { n: 438, t: "Find All Anagrams in a String", d: "Medium", s: "find-all-anagrams-in-a-string" },
  { n: 443, t: "String Compression", d: "Medium", s: "string-compression" },
  { n: 448, t: "Find All Numbers Disappeared in an Array", d: "Easy", s: "find-all-numbers-disappeared-in-an-array" },
  { n: 450, t: "Delete Node in a BST", d: "Medium", s: "delete-node-in-a-bst" },
  { n: 452, t: "Minimum Number of Arrows to Burst Balloons", d: "Medium", s: "minimum-number-of-arrows-to-burst-balloons" },
  { n: 460, t: "LFU Cache", d: "Hard", s: "lfu-cache" },
  { n: 463, t: "Island Perimeter", d: "Easy", s: "island-perimeter" },
  { n: 468, t: "Validate IP Address", d: "Medium", s: "validate-ip-address" },
  { n: 494, t: "Target Sum", d: "Medium", s: "target-sum" },
  { n: 496, t: "Next Greater Element I", d: "Easy", s: "next-greater-element-i" },
  { n: 498, t: "Diagonal Traverse", d: "Medium", s: "diagonal-traverse" },
  { n: 509, t: "Fibonacci Number", d: "Easy", s: "fibonacci-number" },
  { n: 516, t: "Longest Palindromic Subsequence", d: "Medium", s: "longest-palindromic-subsequence" },
  { n: 518, t: "Coin Change II", d: "Medium", s: "coin-change-ii" },
  { n: 523, t: "Continuous Subarray Sum", d: "Medium", s: "continuous-subarray-sum" },
  { n: 530, t: "Minimum Absolute Difference in BST", d: "Easy", s: "minimum-absolute-difference-in-bst" },
  { n: 543, t: "Diameter of Binary Tree", d: "Easy", s: "diameter-of-binary-tree" },
  { n: 547, t: "Number of Provinces", d: "Medium", s: "number-of-provinces" },
  { n: 554, t: "Brick Wall", d: "Medium", s: "brick-wall" },
  { n: 560, t: "Subarray Sum Equals K", d: "Medium", s: "subarray-sum-equals-k" },
  { n: 567, t: "Permutation in String", d: "Medium", s: "permutation-in-string" },
  { n: 572, t: "Subtree of Another Tree", d: "Easy", s: "subtree-of-another-tree" },
  { n: 581, t: "Shortest Unsorted Continuous Subarray", d: "Medium", s: "shortest-unsorted-continuous-subarray" },
  { n: 583, t: "Delete Operation for Two Strings", d: "Medium", s: "delete-operation-for-two-strings" },
  { n: 617, t: "Merge Two Binary Trees", d: "Easy", s: "merge-two-binary-trees" },
  { n: 621, t: "Task Scheduler", d: "Medium", s: "task-scheduler" },
  { n: 622, t: "Design Circular Queue", d: "Medium", s: "design-circular-queue" },
  { n: 647, t: "Palindromic Substrings", d: "Medium", s: "palindromic-substrings" },
  { n: 658, t: "Find K Closest Elements", d: "Medium", s: "find-k-closest-elements" },
  { n: 659, t: "Split Array into Consecutive Subsequences", d: "Medium", s: "split-array-into-consecutive-subsequences" },
  { n: 680, t: "Valid Palindrome II", d: "Easy", s: "valid-palindrome-ii" },
  { n: 684, t: "Redundant Connection", d: "Medium", s: "redundant-connection" },
  { n: 692, t: "Top K Frequent Words", d: "Medium", s: "top-k-frequent-words" },
  { n: 694, t: "Number of Distinct Islands", d: "Medium", s: "number-of-distinct-islands" },
  { n: 695, t: "Max Area of Island", d: "Medium", s: "max-area-of-island" },
  { n: 700, t: "Search in a Binary Search Tree", d: "Easy", s: "search-in-a-binary-search-tree" },
  { n: 701, t: "Insert into a Binary Search Tree", d: "Medium", s: "insert-into-a-binary-search-tree" },
  { n: 703, t: "Kth Largest Element in a Stream", d: "Easy", s: "kth-largest-element-in-a-stream" },
  { n: 704, t: "Binary Search", d: "Easy", s: "binary-search" },
  { n: 706, t: "Design HashMap", d: "Easy", s: "design-hashmap" },
  { n: 707, t: "Design Linked List", d: "Medium", s: "design-linked-list" },
  { n: 724, t: "Find Pivot Index", d: "Easy", s: "find-pivot-index" },
  { n: 733, t: "Flood Fill", d: "Easy", s: "flood-fill" },
  { n: 735, t: "Asteroid Collision", d: "Medium", s: "asteroid-collision" },
  { n: 739, t: "Daily Temperatures", d: "Medium", s: "daily-temperatures" },
  { n: 743, t: "Network Delay Time", d: "Medium", s: "network-delay-time" },
  { n: 746, t: "Min Cost Climbing Stairs", d: "Easy", s: "min-cost-climbing-stairs" },
  { n: 752, t: "Open the Lock", d: "Medium", s: "open-the-lock" },
  { n: 763, t: "Partition Labels", d: "Medium", s: "partition-labels" },
  { n: 778, t: "Swim in Rising Water", d: "Hard", s: "swim-in-rising-water" },
  { n: 785, t: "Is Graph Bipartite?", d: "Medium", s: "is-graph-bipartite" },
  { n: 787, t: "Cheapest Flights Within K Stops", d: "Medium", s: "cheapest-flights-within-k-stops" },
  { n: 844, t: "Backspace String Compare", d: "Easy", s: "backspace-string-compare" },
  { n: 846, t: "Hand of Straights", d: "Medium", s: "hand-of-straights" },
  { n: 853, t: "Car Fleet", d: "Medium", s: "car-fleet" },
  { n: 875, t: "Koko Eating Bananas", d: "Medium", s: "koko-eating-bananas" },
  { n: 876, t: "Middle of the Linked List", d: "Easy", s: "middle-of-the-linked-list" },
  { n: 895, t: "Maximum Frequency Stack", d: "Hard", s: "maximum-frequency-stack" },
  { n: 901, t: "Online Stock Span", d: "Medium", s: "online-stock-span" },
  { n: 907, t: "Sum of Subarray Minimums", d: "Medium", s: "sum-of-subarray-minimums" },
  { n: 909, t: "Snakes and Ladders", d: "Medium", s: "snakes-and-ladders" },
  { n: 912, t: "Sort an Array", d: "Medium", s: "sort-an-array" },
  { n: 918, t: "Maximum Sum Circular Subarray", d: "Medium", s: "maximum-sum-circular-subarray" },
  { n: 930, t: "Binary Subarrays With Sum", d: "Medium", s: "binary-subarrays-with-sum" },
  { n: 973, t: "K Closest Points to Origin", d: "Medium", s: "k-closest-points-to-origin" },
  { n: 981, t: "Time Based Key-Value Store", d: "Medium", s: "time-based-key-value-store" },
  { n: 994, t: "Rotting Oranges", d: "Medium", s: "rotting-oranges" },
  { n: 1004, t: "Max Consecutive Ones III", d: "Medium", s: "max-consecutive-ones-iii" },
  { n: 1011, t: "Capacity To Ship Packages Within D Days", d: "Medium", s: "capacity-to-ship-packages-within-d-days" },
  { n: 1020, t: "Number of Enclaves", d: "Medium", s: "number-of-enclaves" },
  { n: 1046, t: "Last Stone Weight", d: "Easy", s: "last-stone-weight" },
  { n: 1049, t: "Last Stone Weight II", d: "Medium", s: "last-stone-weight-ii" },
  { n: 1071, t: "Greatest Common Divisor of Strings", d: "Easy", s: "greatest-common-divisor-of-strings" },
  { n: 1143, t: "Longest Common Subsequence", d: "Medium", s: "longest-common-subsequence" },
  { n: 1189, t: "Maximum Number of Balloons", d: "Easy", s: "maximum-number-of-balloons" },
  { n: 1199, t: "Minimum Time to Build Blocks", d: "Hard", s: "minimum-time-to-build-blocks" },
  { n: 1203, t: "Sort Items by Groups Respecting Dependencies", d: "Hard", s: "sort-items-by-groups-respecting-dependencies" },
  { n: 1235, t: "Maximum Profit in Job Scheduling", d: "Hard", s: "maximum-profit-in-job-scheduling" },
  { n: 1268, t: "Search Suggestions System", d: "Medium", s: "search-suggestions-system" },
  { n: 1299, t: "Replace Elements with Greatest Element on Right Side", d: "Easy", s: "replace-elements-with-greatest-element-on-right-side" },
  { n: 1343, t: "Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold", d: "Medium", s: "number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold" },
  { n: 1448, t: "Count Good Nodes in Binary Tree", d: "Medium", s: "count-good-nodes-in-binary-tree" },
  { n: 1456, t: "Maximum Number of Vowels in a Substring of Given Length", d: "Medium", s: "maximum-number-of-vowels-in-a-substring-of-given-length" },
  { n: 1480, t: "Running Sum of 1d Array", d: "Easy", s: "running-sum-of-1d-array" },
  { n: 1498, t: "Number of Subsequences That Satisfy the Given Sum Condition", d: "Medium", s: "number-of-subsequences-that-satisfy-the-given-sum-condition" },
  { n: 1584, t: "Min Cost to Connect All Points", d: "Medium", s: "min-cost-to-connect-all-points" },
  { n: 1639, t: "Number of Ways to Form a Target String Given a Dictionary", d: "Hard", s: "number-of-ways-to-form-a-target-string-given-a-dictionary" },
  { n: 1768, t: "Merge Strings Alternately", d: "Easy", s: "merge-strings-alternately" },
  { n: 1851, t: "Minimum Interval to Include Each Query", d: "Hard", s: "minimum-interval-to-include-each-query" },
  { n: 1899, t: "Merge Triplets to Form Target Triplet", d: "Medium", s: "merge-triplets-to-form-target-triplet" },
  { n: 1929, t: "Concatenation of Array", d: "Easy", s: "concatenation-of-array" },
  { n: 1958, t: "Check if Move is Legal", d: "Medium", s: "check-if-move-is-legal" },
  { n: 2013, t: "Detect Squares", d: "Medium", s: "detect-squares" },
  { n: 2092, t: "Find All People With Secrets", d: "Hard", s: "find-all-people-with-secrets" },
  { n: 2130, t: "Maximum Twin Sum of a Linked List", d: "Medium", s: "maximum-twin-sum-of-a-linked-list" },
  { n: 2300, t: "Successful Pairs of Spells and Potions", d: "Medium", s: "successful-pairs-of-spells-and-potions" },
  { n: 2390, t: "Removing Stars From a String", d: "Medium", s: "removing-stars-from-a-string" },
  { n: 2462, t: "Total Cost to Hire K Workers", d: "Medium", s: "total-cost-to-hire-k-workers" },
  { n: 2542, t: "Maximum Subsequence Score", d: "Medium", s: "maximum-subsequence-score" },
];

// Build lookup structures for fast search
// Number map: O(1) lookup by problem number
const byNumber = new Map();
LEETCODE_PROBLEMS.forEach((p) => byNumber.set(p.n, p));

// Search function: matches number prefix or title substring
export function searchProblems(query, limit = 8) {
  if (!query || !query.trim()) return [];
  const q = query.trim();
  const qLower = q.toLowerCase();
  const qNum = parseInt(q, 10);
  const results = [];

  // If query is a number, prioritize exact and prefix number matches
  if (!isNaN(qNum) && q === String(qNum)) {
    // Exact match first
    if (byNumber.has(qNum)) {
      results.push(byNumber.get(qNum));
    }
    // Then prefix matches on number (e.g. "1" matches 1, 10, 11, 12...)
    for (const p of LEETCODE_PROBLEMS) {
      if (results.length >= limit) break;
      if (p.n !== qNum && String(p.n).startsWith(q)) {
        results.push(p);
      }
    }
    // If still room, also match title
    for (const p of LEETCODE_PROBLEMS) {
      if (results.length >= limit) break;
      if (!results.includes(p) && p.t.toLowerCase().includes(qLower)) {
        results.push(p);
      }
    }
  } else {
    // Text search: match title
    for (const p of LEETCODE_PROBLEMS) {
      if (results.length >= limit) break;
      if (p.t.toLowerCase().includes(qLower)) {
        results.push(p);
      }
    }
  }

  return results;
}

// Get a single problem by number
export function getProblemByNumber(num) {
  return byNumber.get(num) || null;
}

// Build URL from slug
export function buildLeetCodeUrl(slug) {
  return `https://leetcode.com/problems/${slug}/description/`;
}

export default LEETCODE_PROBLEMS;
